# Applications

> Progress reports are in inherent part of tracking your progress toward becoming
chartered. You are in a fortunate position though as you should already be
required to write biannual reports for your project. Why not create an annex to this
report which focuses on the DO’s you have achieved.


## Writing Progress Reports

The function of the progress report is to allow your mentor to see the DO’s you have achieved
and for you to start organising your own portfolio on which you will be judged whether you are
ready for the professional review. Get in the habit of marking the DO’s that you are achieving
as you achieve them with just a few sentences and some evidence. This can be such as:

** TABLE **

Now when it comes to writing up the report, it will be easy as you will just have to throw it all
together.

## Report frequency

Most schemes require that you submit a report every 3 months. If you want to follow this then
do so as it’s a tried and tested method. You may be able to just do a development report as
an annex to your biannual report though; this will probably be less time consuming and can
reference your report if need be. It would be advisable to submit a report at least twice a year 
as you will find it difficult to adequately address the entire period and provide insight, 
reviewers will find it hard to follow your development and it shows you are not taking the
process seriously.

## Report length
The reports are quite short and focussed on the specific tasks you have achieved. They need
only be a couple to a few pages in length and should probably not exceed 10 pages excluding
cover, contents and references. You should also include evidence to support your claim of
achievement for the DO in your portfolio and a table showing how far you are in all objectives
as this makes progress easy to see.