# Help! I'm Already a Year or More into My EngD!

> Many people reading this will have already started their EngD and may have
concerns that they have wasted time toward CEng. This is not the case; this
chapter offers some practical exercises which will help you get on track to CEng.

## First things first

Don’t worry about it. Just because you haven’t recorded it doesn’t mean that you haven’t 
done it. You should have project correspondence, reports, papers, possibly journals, 
management plans, a literature review, outputs from tests and an idea of future outputs 
amongst other things. Follow these steps and you should get on track in no time:

1. First things first, map out what DO’s you have achieved to date in each 3 or 6 month 
period and note the specific evidence of this. Do the same for CPD.

1. See if you can get on an accredited company training scheme.

1. Contact your institution and ask for guidance. They may ask you to either:
* Retrospectively create the individual reports.

Or

* Write a single report which covers your experience to date with all supporting evidence.

Either way it will get you on track and in the habit of creating reports and adding to your 
portfolio. You can now continue as if you were following some sort of route the whole time.

Whatever the result, you should start creating your portfolio of evidence.