--- 
title: "The EngD Guide to Chartership"
subtitle: "CEng for EngD"
author: "Michael Rustell"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "A short guide on how you can get chartered through the work you undertake during your Engineering Doctorate"
---

# Preface {-}

Many EngD’s have an educational background in engineering and are interested in becoming
chartered one day but hardly any of the industrial doctoral centres are accredited by the
Engineering Council for *Initial Professional Development* (IPD). This presents a challenge
for the researcher as whilst there is a growing acceptance that the skill and knowledge 
required for registration as a Chartered Engineer are comparable to somebody completing an
industrial doctorate, the process for capitalising on this is ill-defined. This puts 
researchers at risk of not fulfilling their IPD objectives whilst conducting their 
research and missing this opportunity.

Ideally, all centres would achieve accreditation with one or more institutions and a formal
process for CEng registration after successful defence of the viva would exist. Hopefully this
will happen one day, but in the meantime it is up to the individual to drive this process. 
Industrial researchers are usually employed by the university, not the company and sponsoring 
IPD has a cost that must be borne by somebody. Not all companies are willing to pay this additional 
cost, though with planning, this is not going to affect your development nor have a significant cost
to the researcher.

The aim of this document is to offer some guidance on how you can start working toward
CEng whilst conducting industrial research (sponsored by a company) whether your IDC is accredited
for IPD or not and **get chartered in the same amount of time as sombody on a graduate development programme**. 
The process is not rocket-surgery and is in many ways easier than being on a graduate development 
programme. The key is planning and understanding which aspects of your research 
contribute to the relevant objectives for CEng.

This document should not replace your own judgement nor the guidance given by your
institution. You need to become familiar with your institutions guidelines and plan your
development. This guide will however offer practical advice on how to utilise
your time on the EngD toward being chartered and will hopefully enable you to sit your chartered
membership.

# Work in Progress {-}

This book is a work in progress, written in RMarkdown. The source code is located on a Github repo 
[https://github.com/CivilEngineerUK/CEngD.git](https://github.com/CivilEngineerUK/CEngD.git).

Please feel free to pull the code, make suggestions, edits, section requests etc.


# Affiliation {-}

The thoughts and ideas presented in this book are in no way shape or form associated with the
Engineering Council, Institution of Civil Engineers, Institution of Structural Engineers or
any other engineering institution, company or person. They are mine and mine alone and reflect
my own experience and nobody elses. Read this at your own risk and don't take my words as gospel - 
your situation will be different to mine.

# Intended Audience {-}

This book is geared toward people conducting industrial research such as an Engineering Doctorate or
Professional PhD, though has tips for anyone stemming from a research background who wants to become 
chartered. The prose is based from my own experience
negoiating toward CEng with the Institution of Civil Engineers whilst studying for my EngD. 
There is a slight bias toward civil engineering though I've tried to be fairly institutionally neutral as
far as possible.

# My Route {-}

I enrolled on the EngD programme with the *Susainability for Engineering and Energy Systems* (SEES) with the
University of Surrey in 2011. My project was broadly applied artificial intelligence in civil engineering.
I always knew that I would work primarily in industry, though research
did appeal to me and the EngD ticked all the boxes. Upon starting, I was keen to get signed up to
the company training scheme - though there was a catch - I was not an employee and the company did
not fancy paying 4 years of registraion fees for a non-employee on a temporary contract. 
The company did however allow me to follow the scheme unofficialy, including assigning a 
*Delegated Engineer* (DE) as my main point of contact as well as allowing me to meet
the in-house *Supervising Civil Engineer* and the *Regional Development Officer* once a year. 

Still, I knew that I would not be able to complete all objectives through my research alone - some were not
achievable in this role. I did however in the last year, get the university to pay for me to enroll on the
company scheme which allowed me to get a transfer report which essentially validated the entire 4 years
to date and stated that I had achieved 80% of the objectives. As I had not been on the scheme officially,
until now, I did  not have to write quarterly reports - though I did need to write 6-monthly reports as part
of the EngD programme and I used these to demonstrate achievement of objectives.

When I finished the EngD I went to  work as an engineer at a global engineering consultancy, I transferred  
onto their graduate scheme (with 80% of my objectives signed off) and sat and passed my *Chartered Membership
Review* tin 2016.

My EngD provided pretty much all of the experience I needed to become chartered. It required a bit of upfront 
thinking but was a pretty painless process over all and took no less time than the traditional route. 
The kind of work I do now is completely derivative of the research I conducted - the EngD provided me with 
a technical base and problem solving skills that I use on a daily basis. I would recommend insustrial research 
as a platform for an interesting career, with no loss in terms of professional development.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
